"""add is_sample to documents

Revision ID: eff47f9ff933
Revises: 6c06d3b172f6
Create Date: 2025-12-01 09:21:40.142230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff47f9ff933'
down_revision: Union[str, None] = '6c06d3b172f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_sample', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_sample')
    # ### end Alembic commands ###
